### ISSUE TITLE
Other Integration / Telegram Bot

### ISSUE THREAD

**Issue by ghost** [nicolamassarenti/be-dashboard-bert-faqclass#1]
Hi @nicolamassarenti 

Hope you are all well !

I was looking for some implementation of BERT in golang and found your project `bert-faqclass`.

And, I am developing a multibot for telegram based on go plugins: https://github.com/paper2code/telegram-multibot

So I was wondering how can I integrate `bert-faqclass` for a QA plugin.

Do you have any insights or advices for such integration ?

Thanks in advance.

Cheers,
X

**Comment by nicolamassarenti** [comment]
Hi @x0rzkov 

Thank you for your interest! 

The project `bert-faqclass` is composed by 5 elements, now only two of them are exposed as public repositories: they are the frontend (`fe-dashboard-bert-faqclass`) and the backend (`be-dashboard-bert-faqclass`) of a dashboard that has the aim of managing the knowledge base used by BERT for fine-tuning. In particular, the two components allow to manage a set of FAQs, each of which has a set of sentences in different languages, and some context-specific/business-dependent information.

So, to answer your question, the dashboard could help you to manage the knowledge base for your use case and, probably, would require some adaptation.

About the AI: I'm currently working on the model, I'll release the repositories in a few weeks, as soon as I have a stable version. I'm developing a BERT classifier, fine-tuned on the set of FAQ, with a custom extension to manage the context-specific/business-dependent information. The model I'm developing is solving a problem close to yours.
If you need to develop the model asap, my advice is to start with a simple BERT classifier, then to higher-up the complexity if required by the use case.

p.s. `fe-dashboard-bert-faqclass` and `be-dashboard-bert-faqclass` are still WIP, so not all functionalities are already developed.

Cheers,
Nicola

**Comment by ghost** [comment]
Have you tried https://github.com/deepset-ai/haystack ?

I tried it with this repository with fairly good results https://github.com/paper2code/telegram-qa-with-arxiv-papers

Is it something that you can embed easily into your project ?

When do you think that the WIP status will switch to the beta version ?

Cheers,
X

**Comment by nicolamassarenti** [comment]
Never tried, but seems interesting. Thanks!

Yes, it should be simple to integrate in into my project.

Unfortunately I am not able to give an official release date, I'm working on this project during my spare time. I can only anticipate that probably I won't make the repository public before one month.

Nicola

**Comment by ghost** [comment]
Do you mind if we stay in touch via Twitter or Telegram about your project (and not pollute an issue with my questions) ? I am really interested to give a shot.

My telegram is `deepocrates` or Twitter https://twitter.com/x0rzkov
